### ISSUE TITLE
Not seeing the bolus - only carb corrections

### ISSUE THREAD

**Issue by jay-beco** [burnedikt/diasend-nightscout-bridge#26] opened 2023-01-03 19:25 UTC
Was this issue already discussed before? 
It looks like i can only see the carbs correction and not the bolus? Any ideas why?

<img width="2168" alt="image" src="https://user-images.githubusercontent.com/36067186/210427122-3a3fc976-db1f-4c1b-bec2-2a2a5e3ca974.png">

**Comment by burnedikt** [comment] 2023-01-03 19:35
tl; dr; the issue is that the carbs are independently sent to diasend, decoupled from the bolus. This in turn can lead to the situation that the bridge does only see the carbs and not the bolus (which will only appear on diasend later on, when the carbs have already been processed) and send a carb correction to nightscout. Several attempts where made already (e.g. #15) to address this issue but the real solution will be as described in #18.

**Comment by burnedikt** [comment] 2023-01-03 22:37
closing this as it's a duplicate of #18, please follow the progress there.

**Closed as not planned by burnedikt** 2023-01-03 22:37 UTC
